### ISSUE TITLE
Vectors with only y component not showing

### ISSUE THREAD

**Issue by etpinard** [gl-vis/gl-cone3d#1]
From `example/cone.js`, replacing the `createConePlot` call with

```js
var bounds = []
var conePlot = createConePlot({
  positions: [[5,5,5], [-5,-5,-5]],
  vectors: [[0,0.1,0], [0,0.1,0]],
  colormap: 'portland'
}, bounds)
```

gives a blank scene: 

![image](https://user-images.githubusercontent.com/6675409/38441950-738b0466-39b4-11e8-8414-d0a8ef6e2199.png)

**Comment by kig** [comment]
Good catch, the issue was that the cone tangents were calculated using a fixed [0,1,0] up vector. The above commit a31b779 builds the tangents in a more robust manner.
