### ISSUE TITLE
Dependencies should be explicitly set in package.json

### ISSUE THREAD

**Issue by wolfd** [gl-vis/gl-cone3d#15]
Everything directly imported by a file should have a package version set in `package.json`.
I use pnpm, which disallows relying on phantom dependencies, which causes this package to not work correctly.
For more info on phantom dependencies: https://rushjs.io/pages/advanced/phantom_deps/

https://github.com/gl-vis/gl-cone3d/blob/d686777/lib/conemesh.js#L7-L16

The dependencies that should be added to `"dependencies"` in `package.json` are:

- `colormap`
- `gl-buffer`
- `gl-mat4`
- `gl-shader`
- `gl-texture2d`
- `gl-vao`
- `ndarray`
- `normals`
- `simplicial-complex-contour`
- `typedarray-pool`

(this is essentially the same issue as https://github.com/gl-vis/gl-streamtube3d/issues/9)

**Comment by dy** [comment]
@archmoj it should not break anything, but still bumping deps is responsible op

**Comment by archmoj** [comment]
Addressed in 1b6487908b873e3a4a61e0ddcfe1af0439306d0b and 5ee973b24417b32c71c35a3a4dfdfe4c621e2d30.
Published 1.4.0
cc: @etpinard
