### ISSUE TITLE
Cone positioning - tip vs tail vs center of mass

### ISSUE THREAD

**Issue by alexcjohnson** [gl-vis/gl-cone3d#6]
Currently it looks like cones are placed with their tips at the data positions. MATLAB seems to put their tails at the data positions https://www.mathworks.com/help/matlab/ref/coneplot.html. I'd argue that neither is really right, the *center of mass* should be at the data position - ie 1/4 of the way from tail to tip. Or I suppose it could be argued that since these are visually 2D we should do the CM as if it were a 2D shell of a cone, which would be 1/3 of the way from tail to tip. Of course the most flexible would be to make this configurable, maybe some people will really want it this way. But for plotly.js anyway I'd like the default to be some flavor of CM.

@kig is this reasonable?
cc @etpinard @jackparmer

**Comment by kig** [comment]
@alexcjohnson Yeah, this is easily adjustable in the vertex shader that constructs the cones. 

I'll add a uniform to drive it and set the default to 1/4 from the tail.

The reason I went with tips at data positions was that it accurately pinpoints the data positions and creates nice-looking curved shells in some views of the wind dataset.

**Comment by kig** [comment]
d69e33f56100f4d0f81c7f692e8578236790eb37 adds a coneOffset param that ranges from 0 to 1, with 0 placing the cone base at the cone origin, and 1 placing the cone tip at the cone origin. The default is 1/4.

**Comment by alexcjohnson** [comment]
Beautiful, thanks! Indeed, I can see users having different opinions about this, thanks for making it configurable.

@etpinard do you want to check this out in plotly.js before we close this issue?

**Comment by etpinard** [comment]
Looking amazing @kig :tada: 

For cones at [1,1,1], [2,2,2] and [3,3,3] we get:

![peek 2018-05-17 09-39](https://user-images.githubusercontent.com/6675409/40181083-452a6a18-59b6-11e8-9e3b-d9ded88e51da.gif)

with hover labels at the center of mass.
