### ISSUE TITLE
Can't draw single cone

### ISSUE THREAD

**Issue by etpinard** [gl-vis/gl-cone3d#8]
in plotly.js

```js
Plotly.newPlot(gd, [{
  type: 'cone',
  x: [1], y: [1], z: [1],
  u: [1], v: [1], w: [0]
}])
```

or equivalently

```js
var conePlot = createConePlot({
  positions: [[1,1,1]],
  vectors: [[1,1,0]]
})
```
gives a blank screen: 

![image](https://user-images.githubusercontent.com/6675409/40252303-f1b0ff06-5aa9-11e8-9947-4b3dfc1ac830.png)

cc @kig @alexcjohnson

**Comment by alexcjohnson** [comment]
This isn't exactly well-defined with the default `sizemode: 'scaled'` (`coneSize`) (I guess in this case we should default to a minimum cone spacing of 1?) but yeah, it fails with `sizemode: 'absolute'` (`absoluteConeSize`) too.

**Comment by kig** [comment]
My bad, some scaling values were going to Infinity on single-cone graphs. Merged a fix.

I added a second tweak for zero-element graphs, so that they return bounds [[0,0,0], [0,0,0]]. Previous behavior was to return a lot of Infinity.
